version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_DB: kadalcj
      POSTGRES_USER: kadalcj
      POSTGRES_PASSWORD: kadalcj
    ports:
      - "6543:5432"